---
version: "3.7"
services:
  tailscale-nginx:
    image: tailscale/tailscale:latest
    container_name: ${CONTAINER_NAME:-tailscale}
    hostname: tailscale-nginx
    labels:
      - "liveos.appId=tailscale"
    environment:
      # - TS_AUTHKEY=tskey-client-notAReal-OAuthClientSecret1Atawk
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  nginx:
    image: nginx
    container_name: ${CONTAINER_NAME:-tailscale}-nginx
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
    labels:
      - "liveos.helper=true"
